### ISSUE TITLE
Copyright infringement

### ISSUE THREAD

**Issue by BlackCetha** [andrewda/SteamLogin#1]
This entire repository is a modified version of https://github.com/SmItH197/SteamAuthentication .
SteamAuthentication is NOT licensed, meaning all the rights on it are reserved.
You are not even giving credit anywhere.

While i cannot force you to remove the entire repository as I do not hold the rights for SteamAuthentication, I can and hereby do force you to remove my code in the next 2 days.

**Comment by andrewda** [comment]
Thanks for bringing this to my attention.

However, where am I using your code anywhere in this repository?

**Comment by SmItH197** [comment]
Look at all merged pull requests in my repo that were created by @BlackCetha

**Comment by andrewda** [comment]
@BlackCetha @SmItH197 Alright, apologies for the issues. This was one of my first repos and hadn't touched it until today for many months. At the time of creating this, I wasn't experienced enough to fork the official repo, which I'll do now and move the changes made here to that fork.

Thanks!
